#!/usr/bin/env bash

# CPU load shutdown
# While running, this script will monitor the total CPU usage and shutdown the
usage() {
    local SCRIPT_NAME
    SCRIPT_NAME=$(basename "$0")
    echo "usage: $SCRIPT_NAME [-t THRESHOLD] [-s SLEEP_TIME] [-n]"
    echo "Arguments:"
    echo "-t    The CPU load precentage threshold smaller than which the computer will shutdown. (default 0.5)"
    echo "-s    Time in seconds to wait between each check. (default 60)"
    echo "-n    Dry run: if enabled, the computer won't shtdown."
}

# Default values
DRY_RUN=0
THRESHOLD=0.5
SLEEP_TIME=60

# Parse arguments
while getopts "hnt:s:" OPT; do
    case "$OPT" in
        h) # Help
            usage
            exit 0
            ;;
        n) # Dry run
            DRY_RUN=1
            ;;
        t) # Threshold
            THRESHOLD=$OPTARG
            ;;
        s) # Time to sleep
            SLEEP_TIME=$OPTARG
            ;;
        *) # Unknown argument
            usage
            exit 1
            ;;
    esac
done

if [[ $DRY_RUN == 1 ]]; then
    echo "Dry run: computer won't shut down!"
fi

echo "Threshold: ${THRESHOLD}%"
echo "Time interval: ${SLEEP_TIME} seconds"

while :; do
    LOAD=$(uptime | awk -F'[a-z]:' '{ print $2}' | cut -d, -f1)
    echo "CPU load: ${LOAD}%"
    if [[ $(echo "$LOAD < $THRESHOLD" | bc -l) ]]; then
        if [[ $DRY_RUN == 0 ]]; then
            echo "Shutting down..."
            shutdown now
        else
            echo "Load below threshold: computer would shutdown."
        fi
        exit 0
    fi
    sleep "$SLEEP_TIME"
done
