#!/usr/bin/env bash

# Send selected files to dotfiles dir and link them to original location.
usage() {
    local SCRIPT_NAME
    SCRIPT_NAME=$(basename "$0")
    echo "Usage: $SCRIPT_NAME FILES..."
    echo "Send selected files to dotfiles dir and link them to original location."
}

# Parse arguments
while getopts "h" OPT; do
    case "$OPT" in
        h) # Help
            usage
            exit 0
            ;;
        *) # Unknown argument
            usage
            exit 1
            ;;
    esac
done

# Dotfiles repo
export DOTFILES_DIR="$HOME/.dotfiles"

# Program
PROGRAM=$(ls -d $DOTFILES_DIR/*/ | awk -F/ '{ print $(NF-1) }' | fzf --preview='exa --all --tree $DOTFILES_DIR/{}')
# Exit if no program selected
if [[ -z "$PROGRAM" ]]; then
    echo "No directory selected."
    exit 0
fi

for FILE in "$@"; do
    if [[ -f "$FILE" && ! -L "$FILE" ]]; then
        # Path of the new file inside the dotfiles repo
        FILE_PATH=$(realpath "$FILE")
        DOTFILES_FILE_PATH="$DOTFILES_DIR/$PROGRAM/${FILE_PATH#"$HOME/"}"

        # Move file
        echo "Moving: $FILE => $DOTFILES_FILE_PATH"
        mkdir --parents $(dirname "$DOTFILES_FILE_PATH") && mv $FILE_PATH $DOTFILES_FILE_PATH
    else
        echo "Ignoring $FILE: not a file."
    fi
done

# Stow program dotfiles
stow --dir=$DOTFILES_DIR --target=$HOME --stow $PROGRAM --no-folding --verbose
