# Autogenerated config.py
#
# NOTE: config.py is intended for advanced users who are comfortable
# with manually migrating the config file on qutebrowser upgrades. If
# you prefer, you can also configure qutebrowser using the
# :set/:bind/:config-* commands without having to write a config.py
# file.
#
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Change the argument to True to still load settings configured via autoconfig.yml
config.load_autoconfig(False)

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'no-3rdparty', 'chrome-devtools://*')

# Which cookies to accept. With QtWebEngine, this setting also controls
# other features with tracking capabilities similar to those of cookies;
# including IndexedDB, DOM storage, filesystem API, service workers, and
# AppCache. Note that with QtWebKit, only `all` and `never` are
# supported as per-domain values. Setting `no-3rdparty` or `no-
# unknown-3rdparty` per-domain on QtWebKit will have the same effect as
# `all`. If this setting is used with URL patterns, the pattern gets
# applied to the origin/first party URL of the page making the request,
# not the request URL. With QtWebEngine 5.15.0+, paths will be stripped
# from URLs, so URL patterns using paths will not match. With
# QtWebEngine 5.15.2+, subdomains are additionally stripped as well, so
# you will typically need to set this setting for `example.com` when the
# cookie is set on `somesubdomain.example.com` for it to work properly.
# To debug issues with this setting, start qutebrowser with `--debug
# --logfilter network --debug-flag log-cookies` which will show all
# cookies being set.
# Type: String
# Valid values:
#   - all: Accept all cookies.
#   - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
#   - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
#   - never: Don't accept cookies at all.
config.set('content.cookies.accept', 'no-3rdparty', 'devtools://*')

# Value to send in the `Accept-Language` header. Note that the value
# read from JavaScript is always the global value.
# Type: String
config.set('content.headers.accept_language', '', 'https://matchmaker.krunker.io/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0', 'https://accounts.google.com/*')

# User agent to send.  The following placeholders are defined:  *
# `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
# The underlying WebKit version (set to a fixed value   with
# QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
# QtWebEngine. * `{qt_version}`: The underlying Qt version. *
# `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
# QtWebEngine. * `{upstream_browser_version}`: The corresponding
# Safari/Chrome version. * `{qutebrowser_version}`: The currently
# running qutebrowser version.  The default value is equal to the
# unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
# read from JavaScript is always the global value. With QtWebEngine
# between 5.12 and 5.14 (inclusive), changing the value exposed to
# JavaScript requires a restart.
# Type: FormatString
config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')

# Load images automatically in web pages.
config.set('content.images', True, 'chrome-devtools://*')
config.set('content.images', True, 'devtools://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome-devtools://*')
config.set('content.javascript.enabled', True, 'devtools://*')
config.set('content.javascript.enabled', True, 'chrome://*/*')
config.set('content.javascript.enabled', True, 'qute://*/*')

# Cookies
c.content.cookies.accept = "no-3rdparty"
c.content.cookies.store = True

# Default editor
c.editor.command = ["alacritty",
                    "-e",
                    "lvim",
                    "-f",
                    "{file}",
                    "-c",
                    "normal {line}G{column0}l"]

# Disable video autoplay
c.content.autoplay = False

# Ad-blocking
c.content.blocking.enabled = True
c.content.blocking.method = 'both'
c.content.blocking.adblock.lists = ['https://easylist.to/easylist/easylist.txt',
                                    'https://easylist.to/easylist/easyprivacy.txt']
c.content.blocking.hosts.lists = ['https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts']
c.content.blocking.hosts.block_subdomains = True

# Enable dark mode
c.colors.webpage.preferred_color_scheme = 'dark'
c.colors.webpage.darkmode.enabled = True
c.colors.webpage.darkmode.algorithm = 'lightness-cielab'
c.colors.webpage.darkmode.policy.images = 'never'
c.colors.webpage.darkmode.policy.page = 'smart'

# Config search engines
c.url.auto_search = 'naive'
c.url.searchengines["DEFAULT"] = "https://duckduckgo.com/?q={}"
c.url.searchengines["s"] = "https://searx.be/search?q={}&categories=general&language=en-US"
c.url.searchengines["g"] = "https://www.google.com/search?q={}"
c.url.searchengines["b"] = "https://www.bing.com/search?q={}"
c.url.searchengines["yd"] = "https://yandex.com/search/?text={}"
c.url.searchengines["gm"] = "https://www.google.com/maps/search/{}"
c.url.searchengines["wp"] = "https://www.wikiwand.com/en/{}?fullSearch=true"
c.url.searchengines["sp"] = "https://www.startpage.com/sp/search?query={}"
c.url.searchengines["yt"] = "https://www.youtube.com/results?search_query={}"
c.url.searchengines["tw"] = "https://www.twitch.tv/search?term={}"
c.url.searchengines["gs"] = "https://scholar.google.com/scholar?hl=en&q={}"
c.url.searchengines["gd"] = "https://datasetsearch.research.google.com/search?query={}"
c.url.searchengines["lib"] = "http://libgen.rs/search.php?req={}"
c.url.searchengines["sci"] = "https://sci-hub.se/{}"
c.url.searchengines["gh"] = "https://github.com/search?q={}"
c.url.searchengines["h"] = "https://hoogle.haskell.org/?hoogle={}"
c.url.searchengines["r"] = "https://libreddit.spike.codes/r/popular/search?q={}&sort=relevance&t=all"
c.url.searchengines["t"] = "https://nitter.net/search?q={}"
c.url.searchengines["w"] = "https://en.wikipedia.org/w/index.php?search={}"
c.url.searchengines["mw"] = "https://www.merriam-webster.com/dictionary/{}"
c.url.searchengines["th"] = "https://www.thesaurus.com/browse/{}"
c.url.searchengines["so"] = "https://stackoverflow.com/search?q={},"
c.url.searchengines["arch"] = "https://wiki.archlinux.org/index.php?search={}"
c.url.searchengines["apkg"] = "https://archlinux.org/packages/?sort=&q={}&maintainer=&flagged="
c.url.searchengines["aur"] = "https://aur.archlinux.org/packages?O=0&K={}"
c.url.searchengines["tpb"] = "https://thepiratebay.org/search.php?q={}&all=on&search=Pirate+Search&"
c.url.searchengines["ny"] = "https://nyaa.si/?f=0&c=0_0&q={}"
c.url.searchengines["wa"] = "https://www.wolframalpha.com/input/?i={}"
c.url.searchengines["amz"] = "https://www.amazon.com.br/s?k={}"
c.url.searchengines["keepa"] = "https://keepa.com/#!search/12-{}"
c.url.searchengines["color"] = "https://www.color-hex.com/color/{}"
c.url.searchengines["sc"] = "https://www.shellcheck.net/wiki/SC{}"

# Aliases
c.aliases = {   'w': 'session-save --current --only-active-window',
                'q': 'close',
                'qa': 'quit',
                'wq': 'quit --save',
                'wqa': 'quit --save',
                }

# Add libreddit class to hints selectors
c.hints.selectors['libreddit-post'] = ['.post_title']
c.hints.selectors['libreddit-subreddit'] = ['.post_subreddit']
c.hints.selectors['libreddit-user'] = ['.post_author', '.comment_author']

# Read this config.py file
config.bind(',cS', 'config-source')
config.bind(',cE', 'config-edit')

# Dev tools
config.bind('wi', 'devtools bottom')

# Save session
config.bind('<Ctrl+w>', 'session-save --current --only-active-window')
config.bind('<Ctrl+l>', 'set-cmd-text -s :session-load --clear')

# Open in editor
config.bind(',e', 'edit-url')

# Move tabs
config.bind('<Ctrl+Shift+k>', 'tab-move -')
config.bind('<Ctrl+Shift+j>', 'tab-move +')

# Hint yank
config.bind(',y', 'hint all yank')

# Yank link org-mode format [[{link}][{title}]]
config.bind('ym', 'yank inline [[{url}][{title}]]')

# Open links on mpv
config.bind(',p', 'hint links spawn --detach mpv {hint-url}')
config.bind(',P', 'spawn --detach mpv {url}')
config.bind(';p', 'hint --rapid links spawn --detach mpv {hint-url}')

# Download video links
config.bind(',dv', 'hint links spawn --verbose --detach yt-dlp \'{hint-url}\'')
config.bind(',dV', 'spawn --verbose --detach yt-dlp \'{url}\'')
config.bind(';dv', 'hint --rapid links spawn --verbose --detach yt-dlp \'{hint-url}\'')

# Download video links
config.bind(',dm', 'hint links spawn --verbose --detach yt-dlp -f ba -x --audio-format mp3 -o \'~/Storage/Music/_unsorted/%(channel)s - %(title)s [%(id)s].%(ext)s\' \'{hint-url}\'')
config.bind(',dM', 'spawn --verbose --detach yt-dlp -f ba -x --audio-format mp3 -o \'~/Storage/Music/_unsorted/%(channel)s - %(title)s [%(id)s].%(ext)s\' \'{url}\'')
config.bind(';dm', 'hint --rapid links spawn --verbose --detach yt-dlp -f ba -x --audio-format mp3 -o \'~/Storage/Music/_unsorted/%(channel)s - %(title)s [%(id)s].%(ext)s\' \'{hint-url}\'')

# Open webpage on internet archive
config.bind(',a', 'hint links fill :open -t https://web.archive.org/web/{hint-url}')
config.bind(',A', 'open https://web.archive.org/web/{url}')

# Download image in page
config.bind(',di', 'hint --rapid images download')

# Libreddit navigation 
config.bind(',rp', 'hint libreddit-post tab')
config.bind(',rr', 'hint libreddit-subreddit tab')
config.bind(',ru', 'hint libreddit-user tab')
