[[language]]
name = "rust"
auto-format = true

[language-server.julials]
command = "julia"
args = [
    "--project=@helix-lsp",
    "--startup-file=no",
    "--history-file=no",
    "--quiet",
    "/home/evf/.local/bin/julia-lsp.jl",
]

[[language]]
name = "julia"
scope = "source.julia"
injection-regex = "julia"
file-types = ["jl"]
roots = ["Project.toml", "Manifest.toml", "JuliaProject.toml"]
comment-token = "#"
language-servers = [{ name = "julials" }]
indent = { tab-width = 4, unit = "    " }
