return {
    {
        "nvim-treesitter/nvim-treesitter",
        opts = {
            -- add more treesitter parsers
            ensure_installed = {
                "bash",
                "bibtex",
                "c",
                "cpp",
                "cuda",
                "diff",
                "dockerfile",
                "fortran",
                "go",
                "help",
                "html",
                "javascript",
                "json",
                "julia",
                "latex",
                "ledger",
                "lua",
                "luadoc",
                "luap",
                "make",
                "markdown",
                "markdown_inline",
                "norg",
                "python",
                "query",
                "rasi",
                "regex",
                "rust",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "yaml",
            },
        },
    },
}
