#!/usr/bin/env bash

# One of fzf example scripts
usage() {
  local SCRIPT_NAME
  SCRIPT_NAME=$(basename "$0")
  echo "Usage: $SCRIPT_NAME [TEXT]"
  echo "1. Search for text in files current directory using Ripgrep and present results with fzf"
  echo "2. Interactively restart Ripgrep with reload action"
  echo "3. Open the file in NeoVim at the selected line"
}

# Parse arguments
while getopts "h" OPT; do
  case "$OPT" in
    h) # Help
      usage
      exit 0
      ;;
    *) # Unknown argument
      usage
      exit 1
      ;;
  esac
done

RG_PREFIX="rg --column --line-number --no-heading --color=always --smart-case "
INITIAL_QUERY="${*:-}"
IFS=: read -ra selected < <(
  FZF_DEFAULT_COMMAND="$RG_PREFIX $(printf %q "$INITIAL_QUERY")" \
    fzf --ansi \
    --disabled --query "$INITIAL_QUERY" \
    --bind "change:reload:sleep 0.1; $RG_PREFIX {q} || true" \
    --delimiter : \
    --preview 'bat --color=always {1} --highlight-line {2}' \
    --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
)
[ -n "${selected[0]}" ] && nvim "${selected[0]}" "+${selected[1]}"
