# Enable LSP
eval %sh{kak-lsp --kakoune -s $kak_session}  # Not needed if you load it with plug.kak.
hook global WinSetOption filetype=(rust|python|julia|c|cpp) %{
        lsp-enable-window
}

# LSP user mode
map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"

# Colorscheme
colorscheme dracula
